# Copyright (c) 2019-2020 Jürgen Mülbert. All rights reserved.
#
# Licensed under the EUPL, Version 1.2 or – as soon they
# will be approved by the European Commission - subsequent
# versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the
# Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in
# writing, software distributed under the Licence is
# distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.
# See the Licence for the specific language governing
# permissions and limitations under the Licence.
#
# Lizenziert unter der EUPL, Version 1.2 oder - sobald
# diese von der Europäischen Kommission genehmigt wurden -
# Folgeversionen der EUPL ("Lizenz");
# Sie dürfen dieses Werk ausschließlich gemäß
# dieser Lizenz nutzen.
# Eine Kopie der Lizenz finden Sie hier:
#
# https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Sofern nicht durch anwendbare Rechtsvorschriften
# gefordert oder in schriftlicher Form vereinbart, wird
# die unter der Lizenz verbreitete Software "so wie sie
# ist", OHNE JEGLICHE GEWÄHRLEISTUNG ODER BEDINGUNGEN -
# ausdrücklich oder stillschweigend - verbreitet.
# Die sprachspezifischen Genehmigungen und Beschränkungen
# unter der Lizenz sind dem Lizenztext zu entnehmen.

package:
  name: 'jmopenorders'
  version: '0.2.0'

source:
  url: 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
  sha256: 'e0dcc4ed8b63b37d561dfdf8d4f4a436e2b88988df18855b7e84c4ec7716efb8'

build:
  noarch: python
  number: 0
  script: pip install . --no-deps --ignore-installed
  entry_points:
    - jmopenorders = jmopenorders.cli:main

# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#export-runtime-requirements
requirements:
  build:
    - pip
    - python

  run:
    - openpyxl
    - pexpect
    - python
    - python-slugify
    - setuptools

test:
  imports:
    - jmopenorders
    - jmopenorders.openorders
  commands:
    - jmopenorders --help
  requires:
    - tox

about:
  home: https://jmopenorders.github.io/
  license: EUPL-1.2
  license_family: NONE
  license_file: 'LICENSE'
  summary: 'jmopenorders is a generator to generate infos for the affected persons'
  dev_url: https://github.com/jmuelbert/jmopenorders
  doc_url: https://jmopenorders.readthedocs.io

extra:
  recipe-maintainers:
    - jmuelbert
