exclude: "src/jmbde/_vendor/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
        exclude: recipe/meta.yaml
      - id: check-json
      - id: pretty-format-json
        exclude: .vscode/*
      - id: check-xml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      # - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
        exclude: .patch
      - id: check-docstring-first
      - id: fix-encoding-pragma

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.20.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
      - id: mypy
        exclude: docs|tests|jmbde|setup.py
        args: []
        language_version: python3

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations
      # - id: rst-backticks
      #  # Validate existing ReST files and NEWS fragments.
      #  files: .*\.rst$|^news/.*
      #  types:
      #    [file]
      #    # The errors flagged in NEWS.rst are old.
      #  exclude: NEWS.rst

  # - repo: https://github.com/mgedmin/check-manifest
  # rev: "0.40"
  # hooks:
  #  - id: check-manifest

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: bundler-audit
      - id: check-mailmap
      - id: fasterer
      # - id: forbid-binary
      # - id: git-check # Configure in .gitattributes
      - id: git-dirty # Configure in .gitignore
      - id: markdownlint # Configure in .mdlrc
      - id: reek
      - id: rubocop
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      # - id: shellcheck

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
      # - id: dockerfile_lint
      - id: markdown-toc
