default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^.*(\recipe/meta.yaml|\.idea)$
      - id: check-added-large-files
        args: ["--maxkb=150"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
        exclude: ^.*(\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: .vscode/*
      - id: check-xml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
