default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^.*(\recipe/meta.yaml|\.idea)$
      - id: check-added-large-files
        args: ["--maxkb=150"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
        exclude: ^.*(\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: .vscode/*
      - id: check-xml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.1
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-awesome
  #         - flake8-bandit==2.1.2
  #         - flake8-bugbear==20.1.4
  #         - flake8-docstrings==1.5.0
  #         - flake8-rst-docstrings==0.0.13
  #         - pep8-naming==0.10.0
  #         - darglint==1.3.0

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort -y --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system
