default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      #- id: check-yaml
      #  args: ["--allow-multiple-documents"]
      - id: sort-simple-yaml
        exclude: ^.*(\recipe/meta.yaml|\.idea)$
      - id: check-added-large-files
        args: ["--maxkb=150"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
        exclude: ^.*(\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: .vscode/*
      - id: check-xml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: end-of-file-fixer
        stages:
          - commit
          - manual
        exclude: ^.*(\src/jmbde/ui/*.py)$
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^.*(\src/jmbde/ui/*.py)$
        stages:
          - commit
          - manual
      - id: no-commit-to-branch
        args: [--branch, develop]

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
        args: [--application-directories=src]
