exclude: "src/jmbde/_vendor/"

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: check-ast
          - id: check-added-large-files
          - id: check-builtin-literals
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-toml
          - id: check-yaml
            exclude: recipe/meta.yaml
          - id: check-json
          - id: pretty-format-json
            argument: autofix
            exclude: .vscode/*
          - id: check-xml
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-vcs-permalinks
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: name-tests-test
          # - id: double-quote-string-fixer
          - id: requirements-txt-fixer
          - id: forbid-new-submodules
          - id: trailing-whitespace
            exclude: .patch
          - id: check-docstring-first
          - id: fix-encoding-pragma

    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
            args: [
                "--line-length", "80"
                ]

    - repo: https://gitlab.com/PyCQA/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
            additional_dependencies: ["pep8-naming", "flake8-typing-imports"]
            # Ignore all format-related checks as Black takes care of those.
            args: [
                    "--max-line-length", "80",
                    "--ignore", "E2,W5",
                    "--select", "E,W,F,N",

  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.20.0
    hooks:
      - id: validate_manifest

                ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
      - id: mypy
        exclude: docs|tests|jmopenorders|setup.py
        args: []
        language_version: python3

    - repo: https://github.com/asottile/pyupgrade
      rev: v1.25.1
      hooks:
          - id: pyupgrade

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.740
      hooks:
          - id: mypy
            exclude: docs
            # tests|jmopenorders|setup.py
            args: ["--ignore-missing-imports", "--scripts-are-modules"]
            language_version: python3

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: bundler-audit
      - id: check-mailmap
      - id: fasterer
      # - id: forbid-binary
      # - id: git-check # Configure in .gitattributes
      - id: git-dirty # Configure in .gitignore
      - id: markdownlint # Configure in .mdlrc
      - id: reek
      - id: rubocop
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      # - id: shellcheck

    - repo: https://github.com/mgedmin/check-manifest
      rev: "0.40"
      hooks:
          - id: check-manifest

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 1.11.0
      hooks:
          - id: bundler-audit
          - id: check-mailmap
          - id: fasterer
          - id: forbid-binary
          # - id: git-check # Configure in .gitattributes
          - id: git-dirty # Configure in .gitignore
          - id: markdownlint # Configure in .mdlrc
          - id: reek
          - id: rubocop
          - id: script-must-have-extension
          - id: script-must-not-have-extension
          # - id: shellcheck

    - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
      rev: v1.1.0
      hooks:
          - id: dockerfile_lint
          - id: markdown-toc

    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v1.6.0
      hooks:
          - id: setup-cfg-fmt

    - repo: https://github.com/pycqa/pydocstyle
      rev: 4.0.1 # pick a git hash / tag to point to
      hooks:
          - id: pydocstyle
            args:
                - --ignore=D100,D203,D405
