# .readthedocs.yml
name: jmopenorders
type: sphinx
conda:
  file: docs/environment.yml

build:
  image: latest

python:
  version: 3
  setup_py_install: true

requirements_file: requirements_docs.txt
