language: python
python: "3.6"
sudo: required
dist: xenial

env:
  global:
    # used by ci-helpers
    - DEPS="pytest pylint tox coveralls six"
    - MINICONDA_VERSION=latest
    - DISPLAY=":99.0"

  matrix:
    - LINTING=1
    - PYTHON_VERSION=3.6

matrix:
  # PySide2 crashes: #202

install:
  - |
    if [ $LINTING == "1" ]; then
      pip install -U pip
      pip install tox
    else
      # Xvfb / window manager
      sudo apt-get update
      sudo apt-get install -y xvfb herbstluftwm
      # courtesy of https://github.com/astropy/ci-helpers/blob/master/travis/setup_conda_linux.sh
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
      # Setup miniconda
      wget https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda config --add channels conda-forge
      conda config --set always_yes yes --set changeps1 no
      conda create -n test --quiet python=${PYTHON_VERSION} ${DEPS} ${PYQT_PACKAGE}
      source activate test && pip install -e .
    fi
before_script:
  - "herbstluftwm &"
  - sleep 1

script:
  - |
    if [ $LINTING == "1" ]; then
      tox -e linting
    else
      source activate test && catchsegv coverage run --source=jmopenorders -m pytest -v tests
    fi
after_success:
  - coveralls
# deploy:
#  provider: pypi
#  skip_upload_docs: true
#  user: nicoddemus
#  distributions: sdist bdist_wheel
#  password:
#    secure: *
#  on:
#    tags: true
#    repo: pytest-dev/pytest-qt
#    condition: $PYTEST_QT_API = pyqt5
