# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: python

# Use Travis' container-based architecture
sudo: false

services:
  - xvfb

# Turn off email notifications
notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    # The following versions are the 'default' for tests, unless
    # overidden underneath. They are defined here in order to save having
    # to repeat them for all configurations.
    - PIP_DEPENDENCIES='tox'
    - DISPLAY=":99.0"

jobs:
  include:
    - name: "Python 3.8.0 on Bionic Linux"
      dist: bionic
      python: 3.8 # this works for Linux but is ignored on macOS or Windows
      env: TOX_ENV=py38
    - name: "Python 3.6.0 on Xenial Linux"
      dist: xenial
      python: 3.6
      env: TOX_ENV=py36

    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
      language: shell # 'language: python' is an error on Travis CI macOS
      env: TOX_ENV=py37

    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TOX_ENV=py38

install:
  - pip3 install --upgrade pip # all three OSes agree about 'pip3'
  - pip3 install tox
  - pip3 install codecov

script:
    tox -e $TOX_ENV;

after_success:
  - tox -e release
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then
    tox -e report
    fi

deploy:
  provider: pypi
  skip_upload_docs: true
  user: jmuelbert
  password:
    secure: "blWLOCNJ/UuEK2tg4dpgd2pkRvIXlvJmFSv7vF06k+BSacTtRVn5L+syXkcJDjB8eOm1FLBAwlcqt2W6/KACrV0NnfyNj8kuBaIUVrJhWJ+7osoMGJR2tH/TqIFxYFgRs0ZcolfhCVWX0ApRt127526vhUR5m+BLlCRfMlGT4fRgK3Wd7x4YNabjk+t2AHAzDu2v43r95ozxFQALTZHwRg06DrVxuE1eU6QRA6k1mx68DVDmKjjjDVCMCHeTuiqXJ8yPF4btO9mo88B6lMlUQ/grIbY9XTCncscgrZyvuiToERbOeTsQllvVSbl1E2HXcDRBIQR/+M/gy0583Fwf33+cIrITaEtKhe5XU8jykAnW05kcTN81TEKPCxuJYRfkzyZ6+1TDtixniI9/sofwED8cN85yql8xhO44GPPeMfSBLHNAzScd73KhSMz2xDXfWxF9oBjtt3KoEM/v7CVHc+wSuxR/hT/++w2tJgxxxsnX8ntC8zkA7JgAMZn2rgRefYXeR24EQmmWiWJBABlfijYM7SqBEYrEVrV8TOQpfJ09X2CbqNlTMOlqzZBSNHGrMRR4+UsRgAvoYlUXifwRCYr/qY3XJqW8baGRogRYL6ASSTXO/DTC/QVpWqWg57Ey6gejG+NRhCeJsJCm0dzDGTuc3qw/kEHWimY+bX2Xgh0="
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: jmuelbert/jmopenorders
