# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
  - linux

# Use Travis' container-based architecture
sudo: false

# Turn off email notifications
notifications:
  email: false

env:
  global:
    # The following versions are the 'default' for tests, unless
    # overidden underneath. They are defined here in order to save having
    # to repeat them for all configurations.
    - PYTHON_VERSION=3.7
    - PIP_DEPENDENCIES='tox'
    - RUN_CMD='pytest'
    - MINICONDA_VERSION=latest
    - DISPLAY=":99.0"

  matrix:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8

matrix:
  fast_finish: true
  include:
    - env: PIP_DEPENDENCIES='tox twine' TWINE_CHECK=1

    # Try a run on OSX
    - os: osx
      env: PYTHON_VERSION=3.6

    - os: osx
      env: PYTHON_VERSION=3.7

    - os: osx
      env: PYTHON_VERSION=3.8

    # Run a series of tests on Windows
    - os: windows
      env: PYTHON_VERSION=3.6

    - os: windows
      env: PYTHON_VERSION=3.7

    - os: windows
      env: PYTHON_VERSION=3.8

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install .

script: if [[ $TWINE_CHECK ]]; then
  python setup.py build sdist;
  twine check dist/*;
  else
  $RUN_CMD;
  fi

deploy:
  provider: pypi
  skip_upload_docs: true
  user: jmuelbert
  password:
    secure: "blWLOCNJ/UuEK2tg4dpgd2pkRvIXlvJmFSv7vF06k+BSacTtRVn5L+syXkcJDjB8eOm1FLBAwlcqt2W6/KACrV0NnfyNj8kuBaIUVrJhWJ+7osoMGJR2tH/TqIFxYFgRs0ZcolfhCVWX0ApRt127526vhUR5m+BLlCRfMlGT4fRgK3Wd7x4YNabjk+t2AHAzDu2v43r95ozxFQALTZHwRg06DrVxuE1eU6QRA6k1mx68DVDmKjjjDVCMCHeTuiqXJ8yPF4btO9mo88B6lMlUQ/grIbY9XTCncscgrZyvuiToERbOeTsQllvVSbl1E2HXcDRBIQR/+M/gy0583Fwf33+cIrITaEtKhe5XU8jykAnW05kcTN81TEKPCxuJYRfkzyZ6+1TDtixniI9/sofwED8cN85yql8xhO44GPPeMfSBLHNAzScd73KhSMz2xDXfWxF9oBjtt3KoEM/v7CVHc+wSuxR/hT/++w2tJgxxxsnX8ntC8zkA7JgAMZn2rgRefYXeR24EQmmWiWJBABlfijYM7SqBEYrEVrV8TOQpfJ09X2CbqNlTMOlqzZBSNHGrMRR4+UsRgAvoYlUXifwRCYr/qY3XJqW8baGRogRYL6ASSTXO/DTC/QVpWqWg57Ey6gejG+NRhCeJsJCm0dzDGTuc3qw/kEHWimY+bX2Xgh0="
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: jmuelbert/jmopenorders
