# Config file for automatic building at travis-ci.org

language: python
sudo: false

python:
  - "3.6"

matrix:
  fast_finish: true
  include:
    - python: "3.6.1"
      env: TOXENV=lint
    - python: "3.6.1"
      env: TOXENV=pylint
    - python: "3.6.1"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a

  # - conda build conda.receipe --no-test
  # - conda install --use-local repository_name

install:
  - conda create -q -n jmbuild python=$TRAVIS_PYTHON_VERSION
  - source activate jmbuild
  - conda install conda-build anaconda-client pytest pytest-cov tox
  - conda install pexpect openpyxl
  - conda install pip
  - pip install .

script:
  - tox -e lint
  - tox -e pylint
  - tox -e py37
  - tox -e docs

after_success:
  - conda install -c conda-forge codecov
  - codecov
  - coveralls
# deploy:
#  provider: pypi
#  skip_upload_docs: true
#  user: nicoddemus
#  distributions: sdist bdist_wheel
#  password:
#    secure: *
#  on:
#    tags: true
#    repo: pytest-dev/pytest-qt
#    condition: $PYTEST_QT_API = pyqt5
