shallow_clone: false

image:
  - Visual Studio 2017

# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  PYTHONUNBUFFERED: 1
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
  - "%PYTHON%/python -V"
  - mkdir C:\Users\appveyor\.conda
  - call %MINICONDA%\Scripts\activate.bat

install:
  - cmd: "%PYTHON%/Scripts/pip install -U --user pip"
  - cmd: "%PYTHON%/Scripts/pip install -U --user tox wheel"

  - conda list # for debug reason

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - "%PYTHON%/python -m tox -e %TOX_ENV%"
  - tox -e docs

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"

artifacts:
  - path: dist\*

on_success:
  - codecov
