# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:
  global:
    CONDA_PATH: "C:\\Miniconda3-x64"
  matrix:
    - PYTHON_VERSION: "3.7"
      platform: x64

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  # Init and clone submodules
  - git submodule update --init --recursive

  # Clear tmpdir (sometimes left behind by appveyor?)
  - rmdir /s /q %APPVEYOR_BUILD_FOLDER%\\tmp & exit /b 0
    # Setup conda environment
  - "%CONDA_PATH%\\Scripts\\activate.bat"

  # Install the build and runtime dependencies of the project.
  - conda install -q --yes python=%PYTHON_VERSION% conda six pip pytest pytest-xdist pytest-timeout filelock selenium conda-build bzip2
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda install tox
  - conda update -q conda
  - conda info -a
  - python -mpip install pytest-rerunfailures pytest-faulthandler

  # Check that we have the expected version of Python
  - python --version

build_script:
  # In-place build
  - python setup.py build_ext -i

test_script:
  - "%PYTHON%/python.exe tox -e lint"
  - "%PYTHON%/python.exe tox -e pylint"
  - "%PYTHON%/python.exe tox -e cov"
  - "%PYTHON%/python.exe tox -e docs"
