shallow_clone: false

image:
  - Visual Studio 2019

# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  PYTHONUNBUFFERED: 1
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON: "C:\\Python36"
      TOX_ENV: py36
      PYVER: "3.6"

    - PYTHON: "C:\\Python37"
      TOX_ENV: py37
      PYVER: "3.7"

    - PYTHON: "C:\\Python37"
      TOX_ENV: py38
      PYVER: "3.8"

init:
  - "%PYTHON%/python -V"
  - mkdir C:\Users\appveyor\.conda
  - call %MINICONDA%\Scripts\activate.bat
  - python -V
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda update --all

install:
  - conda env create python=%PYVER% -f environment.yml
  - conda activate jmopenorders
  - conda update --all
  - conda list # for debug reason

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - tox

after_test:
  - "python setup.py bdist_wheel"
  - conda build recipe --no-test
  - conda install -q pytest pytest-cov conda-build anaconda-client
  - conda install --use-local jmopenorders
  - conda info -a

artifacts:
  - path: dist\*

on_success:
  - codecov
