shallow_clone: false

image:
  - Ubuntu
  - Ubuntu1804
  - Visual Studio 2015

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      PYTEST_QT_API: "pyside2"
      CONDA_DEPENDENCIES: "pytest-qt pytest pyside2=2.*"
    - PYTHON_VERSION: "3.7"
      PYTEST_QT_API: "pyside2"
      CONDA_DEPENDENCIES: "pytest-qt pytest pyside2=2.*"
    - PYTHON_VERSION: "3.8"
      PYTEST_QT_API: "pyside2"
      CONDA_DEPENDENCIES: "pytest-qt pytest pyside2=2.*"

  global:
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH:
      "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
      # of 32 bit and 64 bit builds are needed, move this
      # to the matrix section.
    # Used by atropy ci-helpers
    CONDA_CHANNELS: "conda-forge"

platform:
  - x64

install:
  # Linux
  - sh: sudo apt update
  - sh: sudo apt -y --force-yes install libglu1-mesa xvfb libgl1-mesa-dri mesa-common-dev libglu1-mesa-dev
  - sh: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sh: bash miniconda.sh -b -p $HOME/miniconda

  # Windows - Miniconda is in Image
  - cmd: set "PATH="C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%"
  - sh: export PATH="$HOME/miniconda/bin;$PATH"
  - conda activate base
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda --yes
  - conda config --set auto_update_conda no
  - conda info -a # for debug reasons
  - conda env create -fcon environment.yml -p conda-env python=${PYTHON_VERSION}
  - cmd: conda-env/bin/activate.bat
  - sh: source conda-env/bin/activate
  - conda list
  - pip install -e .
  - pip install pytest-xvfb pytest-mock pytest-cov pytest-repeat codecov pyvirtualdisplay==0.2.1
  - conda list # for debug reason

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - tox -e ${PYTHON}
  - tox -e docs

on_success:
  - codecov

skip_tags: true
