shallow_clone: false

image:
  - Visual Studio 2017

# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  PYTHONUNBUFFERED: 1
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"
      PYVER: "3.6"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"
      PYVER: "3.7"

init:
  - "%PYTHON%/python -V"
  - mkdir C:\Users\appveyor\.conda
  - call %MINICONDA%\Scripts\activate.bat

install:
  - conda env create python=%PYVER% -f environment.yml
  - conda activate jmopenorders
  - conda update
  - conda list # for debug reason

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - "python -m tox -e %TOX_ENV%"

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*

on_success:
  - codecov
