[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/10431 for the AIX issue.
requires = [
    "setuptools >= 40.0.4",
    "wheel >= 0.29.0"
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 99
