extend = "ruff_defaults.toml"

# https://github.com/astral-sh/ruff/issues/8627
exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv", "dist"]
extend-include = ["*.ipynb"]
preview = true

[format]
docstring-code-format = true

[lint]
ignore = [
  # Allow lazy imports for responsive CLI
  "PLC0415",
]

[lint.pydocstyle]
convention = "google"

[lint.extend-per-file-ignores]
"docs/.hooks/*" = ["INP001", "T201"]

[lint.isort]
known-first-party = ["checkconnect"]