site_name: jmopenorders
site_description: jmopenorders is a generator to generate infos for the affected persons.
site_author: Jürgen Mülbert

theme: readthedocs

repo_url: https://github.com/jmuelbert/jmopenorders

pages:
  - Home: index.md
