{% set name = "jmopenorders" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "e0dcc4ed8b63b37d561dfdf8d4f4a436e2b88988df18855b7e84c4ec7716efb8"

build:
  number: 0
  entry_points:
    - jmopenorders = jmopenorders.__main__:cli
  script: "{{ PYTHON }}" -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - openpyxl
    - pexpect
    - pip
    - python
    - python-slugify
  run:
    - openpyxl
    - pexpect
    - python
    - python-slugify

test:
  imports:
    - jmopenorders
    - jmopenorders.openorders
  commands:
    - jmopenorders --help
  requires:
    - tox

about:
  home: "https://jmopenorders.github.io/"
  license: "European Union Public Licence 1.2 (EUPL 1.2)"
  license_family: "EUPL-1.2"
  license_file: "LICENSE"
  summary: "jmopenorders is a generator to generate infos for the affected persons"
  doc_url: "https://readthedocs.org/projects/jmopenorders/"
  dev_url: "https://github.com/jmuelbert/jmopenorders"

extra:
  recipe-maintainers:
    - jmuelbert
