name: Changelog Validate

on: [pull_request]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog Validate
    steps:
      - uses: actions/checkout@v4
      - uses: zattoo/changelog@v2
        with:
          token: ${{github.token}}
